@id= <the id resulting in the translate call>
@base_url={{$dotenv translate_base_url}} 
@key = {{$dotenv cog_key}}

GET https://{{base_url}}.cognitiveservices.azure.com/translator/text/batch/v1.0/batches/{{id}}/documents
Ocp-Apim-Subscription-Key: {{key}}

 